// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// multiply_hv
List multiply_hv(List l_entries, List r_entries, int N, int k);
RcppExport SEXP _DyadiCpp_multiply_hv(SEXP l_entriesSEXP, SEXP r_entriesSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_hv(l_entries, r_entries, N, k));
    return rcpp_result_gen;
END_RCPP
}
// multiply_vv
List multiply_vv(List l_entries, List r_entries, int N, int k);
RcppExport SEXP _DyadiCpp_multiply_vv(SEXP l_entriesSEXP, SEXP r_entriesSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_vv(l_entries, r_entries, N, k));
    return rcpp_result_gen;
END_RCPP
}
// multiply_hasv
List multiply_hasv(List l_entries, List l_aentries, List r_entries, int N, int k, char type);
RcppExport SEXP _DyadiCpp_multiply_hasv(SEXP l_entriesSEXP, SEXP l_aentriesSEXP, SEXP r_entriesSEXP, SEXP NSEXP, SEXP kSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type l_aentries(l_aentriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< char >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_hasv(l_entries, l_aentries, r_entries, N, k, type));
    return rcpp_result_gen;
END_RCPP
}
// multiply_hsv
List multiply_hsv(List l_entries, List r_entries, int N, int k, char type);
RcppExport SEXP _DyadiCpp_multiply_hsv(SEXP l_entriesSEXP, SEXP r_entriesSEXP, SEXP NSEXP, SEXP kSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< char >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_hsv(l_entries, r_entries, N, k, type));
    return rcpp_result_gen;
END_RCPP
}
// multiply_vh
arma::mat multiply_vh(List l_entries, List r_entries, int N, int k);
RcppExport SEXP _DyadiCpp_multiply_vh(SEXP l_entriesSEXP, SEXP r_entriesSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_vh(l_entries, r_entries, N, k));
    return rcpp_result_gen;
END_RCPP
}
// multiply_vsh
arma::mat multiply_vsh(List l_entries, List r_entries, int N, int k, char type);
RcppExport SEXP _DyadiCpp_multiply_vsh(SEXP l_entriesSEXP, SEXP r_entriesSEXP, SEXP NSEXP, SEXP kSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< char >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_vsh(l_entries, r_entries, N, k, type));
    return rcpp_result_gen;
END_RCPP
}
// multiply_vash
arma::mat multiply_vash(List l_entries, List r_entries, List r_aentries, int N, int k, char type);
RcppExport SEXP _DyadiCpp_multiply_vash(SEXP l_entriesSEXP, SEXP r_entriesSEXP, SEXP r_aentriesSEXP, SEXP NSEXP, SEXP kSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_aentries(r_aentriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< char >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_vash(l_entries, r_entries, r_aentries, N, k, type));
    return rcpp_result_gen;
END_RCPP
}
// multiply_sas
arma::mat multiply_sas(List l_entries, List l_aentries, List r_entries, List r_aentries, int N, int k);
RcppExport SEXP _DyadiCpp_multiply_sas(SEXP l_entriesSEXP, SEXP l_aentriesSEXP, SEXP r_entriesSEXP, SEXP r_aentriesSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type l_entries(l_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type l_aentries(l_aentriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_entries(r_entriesSEXP);
    Rcpp::traits::input_parameter< List >::type r_aentries(r_aentriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_sas(l_entries, l_aentries, r_entries, r_aentries, N, k));
    return rcpp_result_gen;
END_RCPP
}
// asymm_trans
List asymm_trans(List entries, List aentries, int N, int k);
RcppExport SEXP _DyadiCpp_asymm_trans(SEXP entriesSEXP, SEXP aentriesSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type entries(entriesSEXP);
    Rcpp::traits::input_parameter< List >::type aentries(aentriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(asymm_trans(entries, aentries, N, k));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_constr
List rcpp_constr(int height, int breadth, String distr, NumericVector param);
RcppExport SEXP _DyadiCpp_rcpp_constr(SEXP heightSEXP, SEXP breadthSEXP, SEXP distrSEXP, SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    Rcpp::traits::input_parameter< String >::type distr(distrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_constr(height, breadth, distr, param));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_dyad2matrix
arma::mat rcpp_dyad2matrix(List entries, List aentries, int N, int k, std::string type);
RcppExport SEXP _DyadiCpp_rcpp_dyad2matrix(SEXP entriesSEXP, SEXP aentriesSEXP, SEXP NSEXP, SEXP kSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type entries(entriesSEXP);
    Rcpp::traits::input_parameter< List >::type aentries(aentriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_dyad2matrix(entries, aentries, N, k, type));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_dyadalg_core
List rcpp_dyadalg_core(List entries, int N, int k);
RcppExport SEXP _DyadiCpp_rcpp_dyadalg_core(SEXP entriesSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type entries(entriesSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_dyadalg_core(entries, N, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DyadiCpp_multiply_hv", (DL_FUNC) &_DyadiCpp_multiply_hv, 4},
    {"_DyadiCpp_multiply_vv", (DL_FUNC) &_DyadiCpp_multiply_vv, 4},
    {"_DyadiCpp_multiply_hasv", (DL_FUNC) &_DyadiCpp_multiply_hasv, 6},
    {"_DyadiCpp_multiply_hsv", (DL_FUNC) &_DyadiCpp_multiply_hsv, 5},
    {"_DyadiCpp_multiply_vh", (DL_FUNC) &_DyadiCpp_multiply_vh, 4},
    {"_DyadiCpp_multiply_vsh", (DL_FUNC) &_DyadiCpp_multiply_vsh, 5},
    {"_DyadiCpp_multiply_vash", (DL_FUNC) &_DyadiCpp_multiply_vash, 6},
    {"_DyadiCpp_multiply_sas", (DL_FUNC) &_DyadiCpp_multiply_sas, 6},
    {"_DyadiCpp_asymm_trans", (DL_FUNC) &_DyadiCpp_asymm_trans, 4},
    {"_DyadiCpp_rcpp_constr", (DL_FUNC) &_DyadiCpp_rcpp_constr, 4},
    {"_DyadiCpp_rcpp_dyad2matrix", (DL_FUNC) &_DyadiCpp_rcpp_dyad2matrix, 5},
    {"_DyadiCpp_rcpp_dyadalg_core", (DL_FUNC) &_DyadiCpp_rcpp_dyadalg_core, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DyadiCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
