# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiply_hv <- function(l_entries, r_entries, N, k) {
    .Call(`_DyadiCpp_multiply_hv`, l_entries, r_entries, N, k)
}

multiply_vv <- function(l_entries, r_entries, N, k) {
    .Call(`_DyadiCpp_multiply_vv`, l_entries, r_entries, N, k)
}

multiply_hasv <- function(l_entries, l_aentries, r_entries, N, k, type) {
    .Call(`_DyadiCpp_multiply_hasv`, l_entries, l_aentries, r_entries, N, k, type)
}

multiply_hsv <- function(l_entries, r_entries, N, k, type) {
    .Call(`_DyadiCpp_multiply_hsv`, l_entries, r_entries, N, k, type)
}

multiply_vh <- function(l_entries, r_entries, N, k) {
    .Call(`_DyadiCpp_multiply_vh`, l_entries, r_entries, N, k)
}

multiply_vsh <- function(l_entries, r_entries, N, k, type) {
    .Call(`_DyadiCpp_multiply_vsh`, l_entries, r_entries, N, k, type)
}

multiply_vash <- function(l_entries, r_entries, r_aentries, N, k, type) {
    .Call(`_DyadiCpp_multiply_vash`, l_entries, r_entries, r_aentries, N, k, type)
}

multiply_sas <- function(l_entries, l_aentries, r_entries, r_aentries, N, k) {
    .Call(`_DyadiCpp_multiply_sas`, l_entries, l_aentries, r_entries, r_aentries, N, k)
}

asymm_trans <- function(entries, aentries, N, k) {
    .Call(`_DyadiCpp_asymm_trans`, entries, aentries, N, k)
}

rcpp_constr <- function(height, breadth, distr, param) {
    .Call(`_DyadiCpp_rcpp_constr`, height, breadth, distr, param)
}

rcpp_dyad2matrix <- function(entries, aentries, N, k, type) {
    .Call(`_DyadiCpp_rcpp_dyad2matrix`, entries, aentries, N, k, type)
}

rcpp_dyadalg_core <- function(entries, N, k) {
    .Call(`_DyadiCpp_rcpp_dyadalg_core`, entries, N, k)
}

